import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import {ClerkProvider} from '@clerk/nextjs';

import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Container from '@/components/Container';

import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen grid grid-rows-[auto_1fr_auto]`}
				>
					<Header />
					<Container>{children}</Container>
					<Footer />
				</body>
			</html>
		</ClerkProvider>
	);
}
